### ISSUE TITLE
NER evaluation 

### ISSUE THREAD

**Issue by keighrim** [clamsproject/aapb-evaluations#1]
A thread to report and discuss progress on the NER evaluation pipeline development. 

--- 
* AAPB-annotation repo holds upload and “gold” data in separate directories 
* See https://github.com/clamsproject/clams-aapb-annotations/issues/2 and https://github.com/clamsproject/clams-aapb-annotations/issues/9 for details on directory structure
* https://github.com/clamsproject/wgbh-collaboration/issues/21 for details on source data (source data can’t be uploaded in a public repo due to IP/copyright problems)
* https://github.com/clamsproject/app-spacy-nlp is the first app we’d like to evaluate first. 
* https://pypi.org/project/mmif-python/ can be useful to handle MMIF json files

**Comment by keighrim** [comment]
Some questions to @JinnyViboonlarp and @Angela-Lam regarding the progress so far; 

* How do you to handle label sets differences in the gold data and spacy output (if any)? 
* Which format do you assume for the "gold" input? [Currently](https://github.com/clamsproject/clams-aapb-annotations/tree/82c56a4c8a03ab62e7674600bfdf006092dfa932/golds/ner/2022-jun-namedentity/annotations) there are MMIF files in the "gold" directory, but I heard @marcverhagen and @JinnyViboonlarp were discussing the formats last week.

**Comment by JinnyViboonlarp** [comment]
Regarding label differences, the current mapping is  {'PERSON':'person',
'ORG':'organization', 'FAC':'location', 'GPE':'location',
'LOC':'location'}  They
are pretty much 1-to-1 mapping except FAC (countries' names) which
semantically could be either mapped to location or organization based on
contexts.

The current code works with ".ann" format for both gold data and model's
data, but the plan is for me to make it accept input in either .ann or
.mmif (or .json representing a mmif file) format.

**Comment by Angela-Lam** [comment]
To add to Jinny’s email, for the mmif format files, I also plan on having a
1:1 mapping between the predictions and space output. The gold input for
this particular  evaluation task is assumed to have mmif format, and I
think a lot of the code than Jinny wrote can be reused here. I haven't been
able to dig deep into it last week because I was a little swamped by finals
 T-T

**Comment by JinnyViboonlarp** [comment]
Dear Angela,

I just would like to give you a heads-up that I will most likely edit the
evaluation code in a pretty significant way to make it more easily to check
that the implementation is correct (after I’m too less swamped by finals),
so now might not be the best time to dig deep into it.

**Comment by keighrim** [comment]
can you both upload whatever you have done so far to this repo? I guess I need to see what's holding you so long. See this (https://github.com/clamsproject/consumer-evaluation/issues/2#issuecomment-1496963867) to find out how to properly do a push.

**Comment by Angela-Lam** [comment]
Hi Keigh,

I just pushed my progress so far, sorry for the delay! I have one more
assignment due tonight, and 3 more next Wednesday. After that, my schedule
will open up a lot more. I can also meet earlier next week if that works
better for you.

For this code, I still need to change the labels from the MMIF hierarchy to
the entity labels for Spacy. I was able to run it before, but ran into
weird and different bugs the past couple of times trying to run it. For the
next steps, I'll write the label_choice based on the spacy NER labels, and
convert the MMIF format to entity list.

Please let me know what you think.

Best regards,
Angels

**Comment by JinnyViboonlarp** [comment]
Dear Angela,

If it is any relevant, I just uploaded a repo for a conversion between mmif
format and .ann format:
https://github.com/JinnyViboonlarp/ann-mmif-conversion

My plan of the next steps and your plan seems to overlap somewhat, so if I
make any update, I'll let you know as soon as possible to avoid redundancy
in our workflow.

Also,could you send me the link to your updated repo?

Thank you,
Jinny

**Comment by Angela-Lam** [comment]
Hi Jinny,

That's awesome, thank you so much for the helpful information! Here's the
link to my code:
https://github.com/clamsproject/consumer-evaluation/pull/5/files

Best regards,
Angela

**Comment by keighrim** [comment]
@JinnyViboonlarp Hi, we talked about making the evaluation code to work with multiple gold-prediction pairs and return an "aggregated" result. I took your latest code from your personal repo and merged to `main` via #5 into https://github.com/clamsproject/aapb-evaluations/blob/main/ner_eval/evaluate.py . Can you continue updating the code in this repository? Thanks!

**Comment by keighrim** [comment]
done via #12 for now.
