### ISSUE TITLE
Update words/terminology for "preds" and "golds"

### ISSUE THREAD

**Issue by jarumihooi** [clamsproject/aapb-evaluations#40]
### Because

As a subtask of #37, terms/words that refer to the same things should use the same words in the CLAMS projects. The terms will be defined in the eval-repo [README.md](https://github.com/clamsproject/aapb-evaluations/pull/39/files). 
For future code, it is highly recommended to use only the terms "golds" and "preds". 

It is suggested to make the code more readable if the terms become consistent. However, on the other hand, some code may require a good use of multiple variants of the term. Judgement should be used in those cases. 
It is noted that these terms are not obvious as they may seem: A meeting with someone familiar with the project had them ask the question of what "preds" were. 
If a different term is used because it is more appropriate for the context or because it is not the exact same thing, then that is an appropriate use of a different term. 

It is **not currently slated as a priority** to fix occurances below, and readability is not as concerning until new contributors are required to interact with the code here. The different uses are just documented below to show the diversity of term choice. 

====
Within the aapb-eval, these terms are used interchangably for the seemingly the same things: 
golds - refs  
preds/predictions - [results](https://github.com/clamsproject/aapb-evaluations/tree/main/ner_eval/results%40spacy-wrapper%40aapb-collaboration-21), hyps [1](https://github.com/clamsproject/aapb-evaluations/blob/55b53e8c2e12a066c4ab1604b38aa4d7cacec355/asr_eval/asr_eval.py#L40), [2](https://github.com/clamsproject/aapb-evaluations/blob/55b53e8c2e12a066c4ab1604b38aa4d7cacec355/asr_eval/batch_asr_eval.py#L17),  [3](https://github.com/clamsproject/aapb-evaluations/blob/55b53e8c2e12a066c4ab1604b38aa4d7cacec355/asr_eval/README.md?plain=1#L9), [test](https://github.com/clamsproject/aapb-evaluations/blob/55b53e8c2e12a066c4ab1604b38aa4d7cacec355/fa_eval/evaluate.py#L225C5-L225C21), [test output](https://github.com/clamsproject/aapb-evaluations/blob/55b53e8c2e12a066c4ab1604b38aa4d7cacec355/nel_eval/evaluate.py#L10C1-L10C1), [sys-file](https://github.com/clamsproject/aapb-evaluations/blob/55b53e8c2e12a066c4ab1604b38aa4d7cacec355/nel_eval/evaluate.py#L111C9-L111C17), [test files](https://github.com/clamsproject/aapb-evaluations/blob/55b53e8c2e12a066c4ab1604b38aa4d7cacec355/ner_eval/evaluate.py#L333)  
results - this should mean output evaluation results from now on. 

(Note, due to low priority, only 1st 4 projects: asr, fa, nel, ner were reviewed.) 

====
"reference" and "hypothesis" are used in the code [here](https://github.com/clamsproject/aapb-evaluations/blob/55b53e8c2e12a066c4ab1604b38aa4d7cacec355/fa_eval/evaluate.py#L171) for the evaluation of the time frames from which are drawn from golds data and preds data. This is a case likely where it may be unneccesary to consider changes. 

### Done when

- [ ] asr_eval dir has terminology replaced. 
- [ ] fa_eval "^".
- [ ] nel_eval "^".
- [ ] ner_eval "^".
- [ ] ocr_eval "^".
- [ ] timeframe-eval "^".
- [ ] WIP/audioseg_eval "^".
- [ ] WIP/chyrons_eval "^".

### Additional context

Changes made for this issue should be a refactor and have no impact on the running of the code.

**Comment by keighrim** [comment]
#59 fixes this issue by iterating common synonyms of "preds" and "golds" in the README, instead of modifying `evaluate.py` files.
